services:
    # A Docker web service for our WebSocket server
    - type: web
      name: websocket-server
      # 'docker' indicates Render should build from a Dockerfile
      runtime: docker
      # The path to the Dockerfile, relative to the repo root
      dockerfilePath: ./realtime-bitcoin-wallet-tracker-server/Dockerfile
      # The directory to run the build in
      dockerContext: ./realtime-bitcoin-wallet-tracker-server
      # Health Check (optional but recommended)
      # Render will ping this path to make sure your service is up
      healthCheckPath: /health # You would need to implement a simple /health endpoint
      # Environment variables
      envVars:
          - key: KAFKA_BROKERS
            # This 'sync: false' tells Render not to commit the value to the yaml file.
            # You will set this securely in the Render dashboard.
            sync: false
